### ISSUE TITLE
Task :amplitude_react-native:generateDebugRFile FAILED

### ISSUE THREAD

**Issue by nicolascavallin** [amplitude/Amplitude-ReactNative#100]
I'm trying to run `react-native run-android`, and I tried everything (clean cache, remove build and .gradle folders, and re clone the repository), but I can't. The only "red error" that console brings me is:

`> Task :amplitude_react-native:generateDebugRFile FAILED`

I'm running in an Intel Macbook Pro, Big Sur, Node 14, and React Native 0.66.1. 

I think that probably is a general problem, but my partner can run the app in a similar mac without any trouble.

Has anyone had the same mistake?

Thanks

**Comment by AdamTimberlake-Which** [comment]
I receive the same with Gradle 6.9.

![https://i.imgur.com/voGq8w9.png](https://i.imgur.com/voGq8w9.png)

**Comment by yuhao900914** [comment]
@AdamTimberlake-Which 
Just create a brand new app with `npx react-native init AwesomeProject --version 0.66.1`, and install  "@amplitude/react-native": "2.3.2". 
The screenshot is my Gradle Plugin Version  `4.2.2` and Gradle Version `6.9`. The error is not able to reproduce on my end. I'm able to log events in amplitude successfully. 

Can you run `cd android && ./gradlew clean` and have another try?

<img width="491" alt="Screen Shot 2022-02-09 at 11 20 15 PM" src="https://user-images.githubusercontent.com/13028329/153357468-80384769-e816-43e6-8a42-839f8023b6a6.png">

**Comment by AdamTimberlake-Which** [comment]
Try `npx react-native-clean-project` and select yes for all of the Android related options. Should fix it 👍
