### ISSUE TITLE
Request for satisfying documentation

### ISSUE THREAD

**Issue by mtnt** [amplitude/Amplitude-ReactNative#101]
The doc is awful =(
- each method returns a promise with `boolean`, but there is no description what the boolean is... and there is no description when the promise will be resolved/rejected
- how to catch too many request errors? whether the lib resend it automatically or I should manage it by myself?
- how about storing events at app shut down while 429 not resolved yet?
- what is `preappend` method at the [doc](https://developers.amplitude.com/docs/react-native-setup#preappendappend)?

it seems the doc was written very incuriously

**Comment by qingzhuozhen** [comment]
Hi @mtnt Thanks for the feedback. We will try to improve our doc more better. For the ReactNative SDK, right now we are using Android and iOS SDK underlying. So the errors and storage are already handled by these SDKs. The `preappend` seems a typo of `prepend`, that's used for identify a user. However it seems in ReactNative we have just `append` at this moment, I will remove this from our doc for now.
