### ISSUE TITLE
Events not coming through with EU serverZone

### ISSUE THREAD

**Issue by e-verhoeven** [amplitude/Amplitude-ReactNative#103]
Hi there,

I'm currently integration the Amplitude SDK for React Native and I'm having issues with the setServerZone method. If I set the SDK to use the 'EU' serverZone, my events are not coming through (at least not in the UI of Amplitude, e.g. event streams, user events streams, charts etc.). As soon as I switch back to US and rebuild the app, the events are coming through again.

I init Amplitude as follows:
```
const initAmplitude = (): Amplitude => {
  const amplitudeInstance = Amplitude.getInstance();
  amplitudeInstance.init(AMPLITUDE_KEY);
  amplitudeInstance.setServerZone('EU');

  return amplitudeInstance;
}
```

NOTE: I've also tried using the alternative method called setServerUrl('https://api.eu.amplitude.com') as described in the docs, but its not working either.

I'm on version **`@amplitude/react-native": "^2.6.0`** and tested on a real iOS device.

Please look into this issue as we need our data to run on EU servers.

**Comment by haoliu-amp** [comment]
Hello,

All the EU data will be accessible from https://analytics.eu.amplitude.com/

They won't be combined with the US data.

**Comment by e-verhoeven** [comment]
Hi there,

Thank you for your reply. When I attempt to login the EU portal, it says my organization isn't available. Creating a new organization from the EU portal also isn't working. Should I migrate my organization somewhere to the EU region, and if so, how to go about this?

Thank you

**Comment by haoliu-amp** [comment]
I am not quite sure. Would you mind to open a support ticket from [here](https://help.amplitude.com/hc/en-us/requests/new). Our support will try to help.
