### ISSUE TITLE
Test with JEST

### ISSUE THREAD

**Issue by praveshdi** [amplitude/Amplitude-ReactNative#109]
Test suite failed to run

    TypeError: Cannot read property 'getInstance' of undefined

    import { Amplitude } from '@amplitude/react-native';
   
    const ampInstance = Amplitude.getInstance();

**Comment by vasylnahuliak** [comment]
```
import { Amplitude } from '@amplitude/react-native';

jest.mock('@amplitude/react-native', () => ({
  Amplitude: {
    getInstance: jest.fn(),
  },
}));

```

**Comment by yuhao900914** [comment]
Hi @praveshdi ,
Jest is a JavaScript testing tool, it won't run code that has been written in a native module. Our react-native library is a bridge that connects to our native iOS(Objective C) and native Android(Java).  So it won't work. 
Instead, you need to mock the functionality like the above comment. Thanks @vasylnahuliak !
Here is another link you take a look at as a reference. 
https://stackoverflow.com/questions/41339996/how-to-test-a-react-native-component-that-imports-a-custom-native-module-with-je
