### ISSUE TITLE
if send Revenue (local), amplitude console not updated

### ISSUE THREAD

**Issue by OHHAKO** [amplitude/Amplitude-ReactNative#112]
- @amplitude/react-native: ^2.8.0
- react-native: 0.66.4

### What do you want?
- do In-app-purchase in local (e.g sandbox, google Integrity test), amplitude console shows revenue events to me.
- also I can see LTV graph in amplitude console.

### What's problem?
hi guys! appreciate to make good service. I'm using your service in React-Native.
1. I send Revenue to using logRevenue() with local iaps receipt. but amplitude console not showing revenue event. 
This was tested in sandbox and google Integrity environment locally.

2. doesn't make sure i could see LTV graph because in amplitude developer docs said that for tracking iaps, we need to enable revenue verification. but in React-Native SDK there is no method about revenue verification.

i have no idea what can i do for. can i get some advice please?

### Your code

```typescript
function trackRevenue(
  productName: string,
  bill: any
): Promise<void> {
  const { signatureAndroid } = bill;
  console.log('signature: ', signatureAndroid);

  const userProperties: RevenueProperties = {
    price: 7900,
    productId: 'membership',
    quantity: 1,
    receipt: JSON.stringify(bill),
    receiptSignature: signatureAndroid ? signatureAndroid : null,
    eventProperties: {
      product: productName,
    },
  };

  await ampInstance.logRevenue(userProperties);
}
``` 

### Screenshot?

Any Revenue event graph shows just zero in Amplitude console.

<img width="765" alt="스크린샷 2022-03-16 오후 6 20 27" src="https://user-images.githubusercontent.com/29711964/158557627-66c7cacc-2773-44f6-b0be-40b67b2bdcea.png">

**Comment by OHHAKO** [comment]
Hi! type of `receiptSignature` is string (optional).
as you said, i could see Revenue event in User look-up. (not User & Account)


![스크린샷 2022-03-17 오전 11 32 55](https://user-images.githubusercontent.com/29711964/158724885-43db20d6-096d-4b46-a686-a21591ac2353.png)

**Comment by haoliu-amp** [comment]
Have you added the integration with google and apple too?

**Comment by levantsivadze** [comment]
> Hi! type of `receiptSignature` is string (optional). as you said, i could see Revenue event in User look-up! but not User & Account and couldn't find LTV graph properties and options. do you know how to solve it? (e.g Receipt validation, required another settings ..)
> 
> ![스크린샷 2022-03-17 오전 11 39 54](https://user-images.githubusercontent.com/29711964/158725610-d164a3aa-876e-4801-9f99-15956ef00376.png)
> 
> ### Ask you more...
> 1. it means Revenue showing in 'Filter By Events'. but when i selected both, no user log. is it right?
> 2. i wonder Revenue (verified) i think `receipt`, `receiptSignature` property is related on. but `receiptSignature` is android only. want to know What is it for.
> 
> ![스크린샷 2022-03-17 오전 11 32 55](https://user-images.githubusercontent.com/29711964/158724885-43db20d6-096d-4b46-a686-a21591ac2353.png)

Hey, have you figured this out? Facing the same issue in React Native Project. Revenue is shown in Look Up, but can't see it in LTV

**Comment by OHHAKO** [comment]
Hi. @levantsivadze  What plan do you use?
if you want to build a revenue LTV chart, maybe it's not available to free plan. ([docs](https://help.amplitude.com/hc/en-us/articles/230680867))

for track revenue [this docs](https://www.docs.developers.amplitude.com/data/sdks/javascript/#track-revenue) will help you.
in my case, log revenue and it takes for a day to show up into basic chart.
