### ISSUE TITLE
Module works in development, but not in production (expo)

### ISSUE THREAD

**Issue by sreuter** [amplitude/Amplitude-ReactNative#117]
Hi there,

we've added this module to our project and it works well when we try it in our test clients. It does unfortunately not log any errors in production. After further debugging it appears that it doesn't even try to talk to the Amplitude API when logging events.

Anyone else seeing a similar issue?

Cheers,

Sascha

**Comment by Jackman3005** [comment]
Hi @justin-fiedler  (Sascha and I work together).

1. We are using `v2.10.0`
2. Both
3. We have just started using the Amplitude SDK for mobile

We aren't actually able to identify any "error" as such, even when tailing logs in iOS and Android. But we know that events should be logged and zero are logged from any mobile devices.

We are using Expo with EAS builds.

We can see events from mobile devices if we create a developmentClient build and run it on a simulator for example...

**Comment by Jackman3005** [comment]
I have things set up so I can see Android logs of my app, but I'm not finding anything right now on why it wouldn't send an event. Is there a way to turn on debug logging so that all interactions with Amplitude are logged to give us some confidence in what is/isn't working?

**Comment by Jackman3005** [comment]
Hello again. We've identified our issue. **It was our fault**, something got mixed up with the release channels and our updates were not flowing through to prod (doh!). Apologies for any time wasted.

It may still be a good idea to expose the logging level to the RN client though.
