### ISSUE TITLE
Does this work with React Native Web

### ISSUE THREAD

**Issue by travisricks** [amplitude/Amplitude-ReactNative#122]
Can this SDK be used to also track events on sites using React Native Web, or should the JavaScript SDK be used instead?

**Comment by qingzhuozhen** [comment]
Hi @travisricks this SDK now doesn't support React Native Web. We are working on next generation React Native SDK now and plan to support React Native web with it. Will share the updates once the new version is ready. For now you may still need to use Javascript SDK or the new Typescript SDK for web environment. cc @bgiori
