### ISSUE TITLE
How to correctly clean "User ID" property on logout? 

### ISSUE THREAD

**Issue by Deodes** [amplitude/Amplitude-ReactNative#123]
I have a misunderstanding of how to clean "User ID" after calling `Amplitude.getInstance().setUserId("test_user_id")` method. 

The documentation says: 
`"If your app has its own login system that you want to track users with, you can call setUserId at any time."`

There is no problem to set it on user login, but what I suppose to do, when user logout? How can I clean "User ID" to avoid all next events be related to him?

**Comment by qingzhuozhen** [comment]
Hi @Deodes Thanks for asking. You can setUserId to be null and regenerateDeviceId like in https://developers.amplitude.com/docs/android#log-out-and-anonymous-users when logout, so later events are not related.

**Comment by Deodes** [comment]
@qingzhuozhen Thank you for a fast response!
