### ISSUE TITLE
Migrating from expo-analytics-amplitude

### ISSUE THREAD

**Issue by RubenMateus** [amplitude/Amplitude-ReactNative#132]
So I am migrating from expo-analytics-amplitude.

In the expo website https://docs.expo.dev/versions/latest/sdk/amplitude/ they redirect to https://github.com/amplitude/Amplitude-ReactNative.

But once I go to the website for React Native SDK I notice this package is "legacy".
And also there this React Native (Beta).

Which one would you recommend I should change to? i am currently on the fence with this.

Also I tried to update to the legacy but I can't see any way to pass options.

Example code:
```
Amplitude.setTrackingOptions({
  disableCarrier: true,
})
```

Best regards,

**Comment by yuhao900914** [comment]
The [React Native](https://github.com/amplitude/Amplitude-ReactNative) one does not support expo. It's legacy.  [React Native (Beta)](https://github.com/amplitude/Amplitude-TypeScript) is recommended. 

```import { init } from '@amplitude/analytics-react-native';

init(API_KEY, 'user@amplitude.com', {trackingOptions: {xxx}});
```
[The available tracking options are listed here. ](https://www.docs.developers.amplitude.com/data/sdks/react-native-sdk/#opt-users-out-of-tracking)

**Comment by RubenMateus** [comment]
So i guess the expo documentation is somewhat wrong?

https://docs.expo.dev/versions/latest/sdk/amplitude/

**Comment by kevinpagtakhan** [comment]
Hi @RubenMateus, the new [SDK for React Native (Beta)](https://github.com/amplitude/Amplitude-TypeScript/tree/main/packages/analytics-react-native) was just released less than 2 weeks ago. Amplitude follows a guideline on taking new products like this to General Availability (GA) which this SDK has not met yet. However, we feel confident about the quality of this new SDK as it shares a lot of the code with the new [SDK for Browser ](https://github.com/amplitude/Amplitude-TypeScript/tree/main/packages/analytics-browser) which is in General Availability.

**Comment by RubenMateus** [comment]
Thank you for the help!

**Comment by tslater** [comment]
As far as I can tell, there is no [Expo Config Plugin](https://docs.expo.dev/guides/config-plugins/) for either this, or the new beta SDK, is that right?

**Comment by brentvatne** [comment]
> The [React Native](https://github.com/amplitude/Amplitude-ReactNative) one does not support expo.

hey there, I work on Expo and just wanted to clarify some nuance here. in the past, it wasn't possible to use the first-party Amplitude SDK in the Expo managed workflow, which was oriented around a prebuilt runtime in an app called Expo Go. now it's possible to customize the runtime by installing any native module, and then using [development builds](https://docs.expo.dev/development/introduction/) instead of Expo Go. happy to chat with y'all at Amplitude and clarify anything as needed! we confirmed that this SDK does indeed work in development builds, just not in Expo Go (as expected).

> Also i guess the expo documentation is somewhat wrong?

the documentation points to the existing package that is stable, which seemed like the most reasonable thing for us to do here. if the Amplitude team would like me to change [our docs page](https://docs.expo.dev/versions/v45.0.0/sdk/amplitude/) to link to the beta SDK, I can do that!

**Comment by brentvatne** [comment]
> As far as I can tell, there is no [Expo Config Plugin](https://docs.expo.dev/guides/config-plugins/) for either this, or the new beta SDK, is that right?

we did not test against the beta library, but with the current stable library no config plugin is needed. all that's required for installation in that package is to install and link the native library, and the rest is done through your JavaScript application code

**Comment by tslater** [comment]
@brentvatne thanks for the clarification. I'm using EAS build for a custom client with a couple of config plugins. Did you test for EAS build? Other than specifying plugins, I'm not sure how to "link" using EAS to make a custom client for development. Can I just add it to package.json and it will work?

**Comment by brentvatne** [comment]
@tslater - exactly. you don't need to do anything to "link" the library - this is handled automatically in react-native

**Comment by tslater** [comment]
@brentvatne I should have commented earlier. I tried it earlier this evening and it worked. I actually tested the new beta, so I can confirm that works with EAS/a custom client.

**Comment by BrodaNoel** [comment]
I'm adding some comments on https://github.com/expo/expo/pull/18510
