### ISSUE TITLE
A problem occurred evaluating project ':amplitude_react-native'.

### ISSUE THREAD

**Issue by rStarNarayan** [amplitude/Amplitude-ReactNative#133]
* What went wrong:
A problem occurred evaluating project ':amplitude_react-native'.
> Failed to apply plugin 'com.android.internal.library'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.
**_My build.gradle_**
        **firebaseMessagingVersion = "21.1.0" 
        buildToolsVersion = "30.0.3"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 30
        ndkVersion = "22.1.7171670"
        kotlinVersion = "1.5.30"
        androidXAnnotation = "1.1.0"
        androidXBrowser = "1.0.0"
        googlePlayServicesVersion = "17.+"**

**Comment by yuhao900914** [comment]
Hi @rStarNarayan, 
The Android Gradle plugin requires Java 11 to run. But you are currently in Java 1.8.
You need to go to your IDE Gradle setting and change the Gradle JDK change to 11. 
Please check [this](https://github.com/amplitude/Amplitude-ReactNative/issues/95) for how to fix this issue.
