### ISSUE TITLE
Migrating from `amplitude-js` to `@amplitude/react-native`: how to find/use these features?

### ISSUE THREAD

**Issue by bmbmjmdm** [amplitude/Amplitude-ReactNative#141]
I understand that these properties/functions were removed, however wondering if there's an equivalent I should be using, or if they're gone forever:

- the ability to pass `trackingOptions: { ip_address: false }`, which would previously be done in the `init` function
- setVersionName, which is obviously removed now but I would still like to track which version users are on

Thank you!

**Comment by justin-fiedler** [comment]
Hi @bmbmjmdm at this time those options are not available in the new SDK. I have made a ticket to re-add support and will keep you posted on updates. Thank you.

**Comment by bmbmjmdm** [comment]
Thanks for the quick reply @justin-fiedler . Is there anything I can do/contribute to help speed these features up?

**Comment by justin-fiedler** [comment]
Hi @bmbmjmdm, this SDK in `Amplitude-ReactNative` doesn't support trackingOptions, however our new ReactNative SDK implemented in `Amplitude-TypeScript` repository does. 

The new TS RN SDK will be the primary RN SDK going forward so we recommend updating to get the latest features and bug fixes. Here are some resources on the new SDK. Hope this helps.

TS RN SDK Docs - https://www.docs.developers.amplitude.com/data/sdks/typescript-react-native/
TS RN SDK Repo - https://github.com/amplitude/Amplitude-TypeScript/tree/main/packages/analytics-react-native
Tracking Options -  https://www.docs.developers.amplitude.com/data/sdks/typescript-react-native/#optional-tracking
Version name can now be set via "appVersion" - https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-types/src/config.ts#L32

**Comment by bmbmjmdm** [comment]
Hey thanks! I actually found TS RN SDK this morning. I'm currently trying it out!
