### ISSUE TITLE
[iOS] Build Failed in Xcode 14 with React Native 0.70.1

### ISSUE THREAD

**Issue by plush-mesh** [amplitude/Amplitude-ReactNative#142]
Cannot compile the project in Xcode 14.0 because of an error which arises in `AMPServerZone.h`. The compilation worked fine in Xcode 13.4.1 and Xcode 14.0 before the migration to RN 0.70.1. Our project uses only Objective-C.
I suppose the situation somehow relates to Compiler Options in Build Settings in the new version of Xcode. Maybe the new version of RN set them.

When I comment out or remove line 31 the error is gone and the project compiles successfully.
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/16272113/191083573-9b8c2358-5a16-4a0a-8b05-a08db2a76bd9.png">

These are [the changes](https://react-native-community.github.io/upgrade-helper/?from=0.66.4&to=0.70.1) that were applied during migration to `OTHER_CPLUSPLUSFLAGS` in Build Settings of [`project.pbxproj`](https://raw.githubusercontent.com/react-native-community/rn-diff-purge/release/0.70.1/RnDiffApp/ios/RnDiffApp.xcodeproj/project.pbxproj) as in React Native Upgrade Helper, excluding `EXCLUDED_ARCHS` and `IPHONEOS_DEPLOYMENT_TARGET`.
<img width="777" alt="image" src="https://user-images.githubusercontent.com/16272113/191204195-2fcf086f-be86-461c-a733-59e6137221eb.png">

**Prerequisites:**
- macOS 12.6, Intel
- Xcode 14.0
- CocoaPods 1.11.3
- `use_frameworks!` is disabled in Podfile (I wish to enable it later)
- React Native 0.70.1
- New Architecture is disabled
- `@amplitude/react-native` 2.13.0

**Comment by yuhao900914** [comment]
Hi @artnest. Thanks for choosing amplitude.
I'm able to build and run the project successfully using Xcode 14.0.1.  and the same CocoaPods, RN version, @amplitude/react-native with you.
Does this issue still exist, can you try to update the Xcode version?

**Comment by artnest** [comment]
> Hi @artnest. Thanks for choosing amplitude.
> I'm able to build and run the project successfully using Xcode 14.0.1, and the same CocoaPods, RN version, @amplitude/react-native with you.
> Does this issue still exist, can you try to update the Xcode version?

The issue still exists, unfortunately. I've updated Xcode to 14.0.1 and tried building the app in the same environment, both RN 0.70.1 and the newly 0.70.4. The error is exactly the same as in the original screenshot.

**Comment by yuhao900914** [comment]
@artnest , Can you provide an example app since I cannot reproduce it on my end?
 
A side question which os system are you using?

**Comment by plush-mesh** [comment]
Many versions passed, the issue is no longer actual. Seems like resolved, works with the latest versions of everything involved.
