### ISSUE TITLE
Error: import undefined.AmplitudeReactNativePackage;

### ISSUE THREAD

**Issue by andrew-skrypnyk** [amplitude/Amplitude-ReactNative#169]
After installing Amplitude
```sh
npm install @amplitude/analytics-react-native
npm install @react-native-async-storage/async-storage
```
 
 And building the app I got this error:

File path: `com/facebook/react/PackageList.java`
`app/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java`

```java
// @amplitude/react-native
import undefined.AmplitudeReactNativePackage;
```

```
      new AmplitudeReactNativePackage(),
          ^
  symbol:   class AmplitudeReactNativePackage
  location: class PackageList
```

![CleanShot 2023-08-15 at 13 08 56@2x](https://github.com/amplitude/Amplitude-ReactNative/assets/5373730/21ca9fc1-fcaf-438b-8677-8381e58846cb)

**Comment by justin-fiedler** [comment]
Hi @andrew-skrypnyk thanks for choosing Amplitude.

This repo is for our [maintenance RN SDK](https://www.docs.developers.amplitude.com/data/sdks/react-native/). The new repo is here:
https://github.com/amplitude/Amplitude-TypeScript/tree/v1.x/packages/analytics-react-native

What version of React Native are you using? Versions of the SDK < 1.4 don't support the latest RN & RN CLI. Can you please updating to the latest version and see if that resolves the issue.

https://www.docs.developers.amplitude.com/data/sdks/typescript-react-native/#compatibility-matrix

Thanks!

**Comment by samcasmmm** [comment]
error: package undefined does not exist
import undefined.AmplitudeReactNativePackage;

still getting error can you please help me ?

`BUILD FAILED in 1m 11s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
C:\Users\Sameer\Desktop\hookfish\newhookfishapp\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:15: error: package undefined does not exist
import undefined.AmplitudeReactNativePackage;
                ^
C:\Users\Sameer\Desktop\hookfish\newhookfishapp\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:143: error: cannot find symbol
      new AmplitudeReactNativePackage(),
          ^
  symbol:   class AmplitudeReactNativePackage
  location: class PackageList
Note: C:\Users\Sameer\Desktop\hookfish\newhookfishapp\android\app\src\debug\java\com\hookfishforpartners\ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 11s

    at makeError (C:\Users\Sameer\Desktop\hookfish\newhookfishapp\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at C:\Users\Sameer\Desktop\hookfish\newhookfishapp\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (C:\Users\Sameer\Desktop\hookfish\newhookfishapp\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\Sameer\Desktop\hookfish\newhookfishapp\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.`


please help !! RN : 0.65
