### ISSUE TITLE
Missing "eventProperties" param in logEvent()

### ISSUE THREAD

**Issue by dafrie** [amplitude/Amplitude-ReactNative#34]
Thanks for this new official RN SDK, well appreciated!
Quick question on the event tracking: Currently no optional `eventProperties` can be passed to `logEvent()`, which deviates from the JS/native SDK's. Is there a plan to allow passing this param in the future? Because I see that at least there are some comments in the code :)

https://github.com/amplitude/Amplitude-ReactNative/blob/49b9f439f0a8d78e126553bcad40271208b90559/src/index.ts#L49

**Comment by yuhao900914** [comment]
Thanks for bring this issue up. Will put this into schedule. 
I will let you know when we have new release with `eventProperties` implemented. 
Thanks,
Hao

**Comment by kelsonpw** [comment]
Going to release a 2.0.2 version that fixes this

**Comment by kelsonpw** [comment]
@dafrie v2.0.2 has been released with support for passing event properties to logEvent

**Comment by dafrie** [comment]
amazing, thank you for the quick fix!

**Comment by kelsonpw** [comment]
Not a problem @dafrie thanks so much for filing!  Please file as many issues as you want, it helps us build the best SDK possible for our users :)
