### ISSUE TITLE
Swift pod error

### ISSUE THREAD

**Issue by sshvaiko** [amplitude/Amplitude-ReactNative#40]
Hello, I'm getting this error when I install the package:
``` The Swift pod `amplitude-react-native` depends upon `Amplitude`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.```

Could you help with that?

**Comment by yuhao900914** [comment]
Hi @sshvaiko. 
Under the root directory, please go to ios folder. Edit the Podfile file, and add the following code in.
```
use_modular_headers!
use_frameworks!
```
That will fix the issue. 
Thanks,
Alyssa.

**Comment by sshvaiko** [comment]
Hi @yuhao900914 do you know that use_frameworks is incompatible with Flipper?
`# Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.`

**Comment by yuhao900914** [comment]
Thanks for point it out. We are dealing with this issue. 
We will give you an update after we have the solution. 
Thanks.

**Comment by angel-discover** [comment]
use_frameworks! gives me an error when using FirebasePerformance library, will stick with the amplitude-js lib for now

**Comment by yuhao900914** [comment]
Hi @sshvaiko,
In the Flipper app, there is one thing related what should we do if we use use_frameworks!. Could you try to add use_frameworks! and uncomment the $static_framework array and also # the pre_install section in Flipper?

```
  # If you use `use_frameworks!` in your Podfile,
  # uncomment the below $static_framework array and also
  # the pre_install section.  This will cause Flipper and
  # it's dependencies to be built as a static library and all other pods to
  # be dynamic.
  #
  # NOTE Doing this may lead to a broken build if any of these are also
  #      transitive dependencies of other dependencies and are expected
  #      to be built as frameworks.
```
(https://fbflipper.com/docs/getting-started/ios-native/)

**Comment by Cigan12** [comment]
I have the same issue, and if I am adding use_modular_headers! and use_frameworks! it throws me an error Undefined symbol: _YGValueUndefined, what I can do?)

**Comment by alexmngn** [comment]
Same issue here 👋 
I cannot turn on `use_frameworks!` otherwise it completely fails to compile my other dependencies such as Firebase.

**Comment by Kladislav** [comment]
This library is absolute broken cause using use_frameworks! and use_modular_headers!

**Comment by nedba** [comment]
I have the same issue

**Comment by yuhao900914** [comment]
Thanks for reporting this issue. 
We are currently working on finding a way to avoid this requirement to allow for Flipper Support, but as of now it is required. Updates coming soon.

**Comment by Kladislav** [comment]
temporary replacement is https://docs.expo.io/versions/latest/sdk/amplitude/

**Comment by payucads** [comment]
> temporary replacement is https://docs.expo.io/versions/latest/sdk/amplitude/

Hi @Kladislav ,
I followed all of their instruction & managed to install everything successfully, but I'm still not receiving any events (that I've implemented). Do you have any advices/experiences on how to handle that - and/or - which data source should be used here, since Javascript SDK is not picking up any events while listening?

Thank in advance!

**Comment by Kladislav** [comment]
@payucads Idk, the the expo library working fi e, all what i did is follow expo documentation. Can you show your code?

**Comment by payucads** [comment]
> @payucads Idk, the the expo library working fine, all what i did is follow expo documentation. Can you show your code?

@Kladislav Unfortunately, I can't (company rules). But I tested the installation of unimodules and it was installed properly. Same with expo-analytics-amplitude. Did you do it in an expo app or bare react native app? Mine is a bare RN app. 
Also which data source did you choose for this (Javascript SDK)? Thanks!

**Comment by kelsonpw** [comment]
@sshvaiko @payucads ￼

We have made changes that removed the requirement to make any changes to your Podfile.  Try redownloading the @amplitude/react-native@latest (v2.0.9) and removing both use_modular_headers! And use_frameworks!.  After that I expect the issues should be non existent.

**Comment by kelsonpw** [comment]
> @sshvaiko @payucads ￼
> 
> We have made changes that removed the requirement to make any changes to your Podfile.  Try redownloading the @amplitude/react-native@latest (v2.0.9) and removing both use_modular_headers! And use_frameworks!.  After that I expect the issues should be non existent.

Vv @Kladislav

**Comment by kelsonpw** [comment]
If you run into installation issues after upgrading to v2.0.9 see my response in issue #46

**Comment by kelsonpw** [comment]
@sshvaiko Closing this for now since this issue has been reported as resolved.  If you run into issues please try following my response linked above.  I'll gladly reopen if you continue having issues after trying the listed options.

**Comment by Revolt9k** [comment]
Problem still here. Amplitude 8.2.0 and amplitude-react-native 2.3.3 throws that error. None of workarounds helped. Any other suggestions?

**Comment by Revolt9k** [comment]
> Problem still here. Amplitude 8.2.0 and amplitude-react-native 2.3.3 throws that error. None of workarounds helped. Any other suggestions?


After a couple hours of struggling I found a solution. Add 
```   
use_modular_headers!
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec', :modular_headers => false
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec', :modular_headers => false
``` 
and clear pod cache with

```
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
rm -rf ~/Library/Developer/Xcode/DerivedData/*
pod deintegrate
pod setup
pod install
```

**Comment by Lov9766** [comment]
Using Expo modules
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Auto-linking React Native modules for target `project2`: RNFBApp and RNFBAuth
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
Analyzing dependencies
[Codegen] Found FBReactNativeSpec
Downloading dependencies
Installing Firebase (9.1.0)
Installing FirebaseAuth (9.1.0)
Installing FirebaseCore (9.1.0)
Installing FirebaseCoreDiagnostics (9.2.0)
Installing FirebaseCoreInternal (9.2.0)
Installing GTMSessionFetcher (2.0.0)
Installing GoogleDataTransport (9.1.4)
Installing GoogleUtilities (7.7.0)
Installing PromisesObjC (2.1.1)
Installing RNFBApp (15.0.0)
Installing RNFBAuth (15.0.0)
Installing nanopb (2.30909.0)
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `FirebaseCoreInternal` depends upon `GoogleUtilities`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

**Comment by Lov9766** [comment]
please suggest solution

**Comment by hassanannajjar** [comment]
> please suggest solution

I fixed the same problem like this

1- make a sure the version for your firebase message and app it's 14

```
 "@react-native-firebase/app": "^14.2.2",
 "@react-native-firebase/messaging": "^14.2.2",
```

2- remove `node_modules` and (`yarn.lock` or `package-lock.json` ) 
3- (`yarn install` or `npm i`)
4- 
```
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
rm -rf ~/Library/Developer/Xcode/DerivedData/*
pod deintegrate
pod setup
pod install --repo-update
```
5- `pod update Firebase/CoreOnly`

**Comment by Shrroy** [comment]
@hassanannajjar 
"Downgrading of course works, but that's the same as saying "the new version is a bit difficult so not using it avoids the difficulty", in other words, it is a tautology --> 1 = 1. For anyone that needs to do this I do understand, but please pay attention to this issue for progress so you can successfully move on to future version versus being stuck forever on the old stuff.." //mikehardy
