### ISSUE TITLE
Error 'CocoaPods could not find compatible versions for pod "amplitude-react-native"'

### ISSUE THREAD

**Issue by ALPNP** [amplitude/Amplitude-ReactNative#44]
**Environment:**
macOS Catalina: 10.15.4
node: 14.15.5
pod: 1.9.3

**Packages:**
"@amplitude/react-native": "^2.0.6"
"react-native": "0.61.4"

**Reproduce:**
Run `npm install @amplitude/react-native`
Run `react-native start`

**Expected result:**
The app was built successfully

**Result:**
![Снимок экрана 2021-03-15 в 14 06 39](https://user-images.githubusercontent.com/18089606/111144110-acc3c880-8597-11eb-8dd9-13c9af2dc450.png)

When `pod install` command run got error:
<img width="571" alt="Снимок экрана 2021-03-15 в 14 44 16" src="https://user-images.githubusercontent.com/18089606/111148635-ecd97a00-859c-11eb-99e7-01967c05845d.png">

Thx.

**Comment by yuhao900914** [comment]
Hi @ALPNP,
Before doing the `pod install`, please add the following code to your `Podfile`.
```
use_modular_headers!
use_frameworks!
```
We are working on taking out these setting on our end, but for now those are needed.
Thanks.

**Comment by ALPNP** [comment]
Hi @yuhao900914, thx for the answer.

After add following code to my `Podfile` and run `pod install`, I have same error:

<img width="574" alt="Снимок экрана 2021-03-16 в 12 22 19" src="https://user-images.githubusercontent.com/18089606/111285508-418afc80-8652-11eb-88e2-658eed6b058a.png">

My Podfile:

![Снимок экрана 2021-03-16 в 12 34 38](https://user-images.githubusercontent.com/18089606/111287321-27521e00-8654-11eb-965e-cfc78ed438ea.png)

**Comment by kelsonpw** [comment]
We have made changes that removed the requirement to make any changes to your Podfile.  Try redownloading the @amplitude/react-native@latest (v2.0.9) and removing both use_modular_headers! And use_frameworks!.  After that I expect the issues should resolve themselves.

**Comment by kelsonpw** [comment]
> We have made changes that removed the requirement to make any changes to your Podfile.  Try redownloading the @amplitude/react-native@latest (v2.0.9) and removing both use_modular_headers! And use_frameworks!.  After that I expect the issues should resolve themselves.

cc @ALPNP

**Comment by kelsonpw** [comment]
If you run into installation issues after upgrading to v2.0.9 see my response in issue #46

**Comment by kelsonpw** [comment]
@ALPNP Closing this now.  If you still run into minimum deployment target issues please feel free to file another issue to prompt a discussion on our current minimum requirements.
