### ISSUE TITLE
Pod install error: target has transitive dependencies

### ISSUE THREAD

**Issue by cnhsttyle** [amplitude/Amplitude-ReactNative#46]
I Added use_modular_headers! and use_frameworks! to the top of my Podfile.

After that I did "pod install"
But It gives me an error
: The 'Pods-App' target has transitive dependencies that include statically linked binaries: (FirebasePerformance)

how can i solve it?
<img width="604" alt="스크린샷 2021-03-16 오후 3 21 17" src="https://user-images.githubusercontent.com/15974698/111264710-5f189000-866b-11eb-8038-d22ed2724656.png">

**Comment by rorygarand** [comment]
I followed the installation steps to the letter and I am getting the same exact error.

Can anyone from the Amplitude team provide some guidance?

**Comment by ethanneff** [comment]
It's broken for me as well. I just used the javascript library instead https://developers.amplitude.com/docs/javascript

**Comment by payucads** [comment]
Same here. I would really appreciate some input from the Amplitude team.

**Comment by kelsonpw** [comment]
We have made changes that removed the requirement to make any changes to your Podfile.  Try redownloading the @amplitude/react-native@latest (v2.0.9) and removing both use_modular_headers! And use_frameworks!.  After that I expect the issues should be non existent.

**Comment by payucads** [comment]
> We have made changes that removed the requirement to make any changes to your Podfile. Try redownloading the @amplitude/react-native@latest (v2.0.9) and removing both use_modular_headers! And use_frameworks!. After that I expect the issues should be non existent.

@kelsonpw hey! thanks for the answer. I did everything you said and now I'm getting this error:
<img width="943" alt="Screenshot 2021-03-19 at 15 51 44" src="https://user-images.githubusercontent.com/30795120/111799288-2a0a7880-88cb-11eb-999a-4385437dbffe.png">

**Comment by kelsonpw** [comment]
@payucads this happened me while testing the fix.  The cause is related to podfile cache.  Try running pod either:

`pod repo update && pod install`
`pod install --repo uodate`

Or if neither of those above worked (they worked for me in a separate project.

If this still doesn't resolve the installation issue, worst case try deleting your Pod folder and your Podfile.lock.

The goal is to install v2.0.9 which had Amplitude 8.2.0 as a sub dependency (the fix actually came from the Amplitude pod so having 8.2.0 is important.

**Comment by rorygarand** [comment]
Really appreciate the support @kelsonpw.

I also needed to reset the pod cache, but afterwards everything worked like a charm.

Thanks!

**Comment by kelsonpw** [comment]
@rorygarand not a problem.  Glad to hear things are working properly.  Please feel free to file an issue if you run any problems/concerns/questions.  Cheers!

**Comment by akinncar** [comment]
Hi @kelsonpw how did you change the library to doesn't need use_frameworks anymore? I'm trying to do this in another library.

**Comment by ejoo** [comment]
Deleting both the pod folder and Podfile.lock helped me over this issue.
