### ISSUE TITLE
Error: 'CocoaPods could not find compatible versions for pod "amplitude-react-native"' on react-native version 0.61.4

### ISSUE THREAD

**Issue by ALPNP** [amplitude/Amplitude-ReactNative#56]
Previous issue https://github.com/amplitude/Amplitude-ReactNative/issues/44

Environment:
macOS Catalina: 10.15.4
node: 14.15.5
pod: 1.10.1

Packages:
"@amplitude/react-native": "^2.0.11"
"react-native": "0.61.4"

Reproduce:
Run `npm install @amplitude/react-native@latest`
Run `cd ios && pod install`

Expected result:
Command `pod install` successfully

Result:
<img width="584" alt="Снимок экрана 2021-03-23 в 18 10 08" src="https://user-images.githubusercontent.com/18089606/112169178-02851a00-8c03-11eb-9e1f-6f51cbdb6bc1.png">

I tried run commands from issue https://github.com/amplitude/Amplitude-ReactNative/issues/46 , but it didn't solve my problem.

If I create an empty project via `npx react-native init AwesomeProject` command (react-native version 0.64.0) everything works:
<img width="584" alt="Снимок экрана 2021-03-23 в 19 02 44" src="https://user-images.githubusercontent.com/18089606/112177879-5c3d1280-8c0a-11eb-8709-cc356c050b44.png">

If I create an empty project via `npx react-native init AwesomeProject --version 0.61.4` command  (react-native version 0.61.4) I get an error:
<img width="584" alt="Снимок экрана 2021-03-23 в 18 58 25" src="https://user-images.githubusercontent.com/18089606/112177158-c0aba200-8c09-11eb-9242-7730c2c28c5f.png">

There is no information about this issue in the documentation https://developers.amplitude.com/docs/react-native-setup
Please provide information on what is the minimum version of react-native that can be used.

Thx.

**Comment by kelsonpw** [comment]
Hi @ALPNP.  We support 0.61 and higher.  We are currently updating the documentation around older versions, thanks for your patience as we get those written.

In the meantime, here's a solution that worked for a user on 0.61.5

1. fix part one - xcode:
  - Open your `[project-name].xcodeproj` file in XCode
  - Right Click your project name in the file navigator and then click New File, pick swift, it will then prompt you to creating a bridging headers file.  This is necessary to support swift in RN 0.61.5.

  - Source of this fix: https://stackoverflow.com/a/54586937

2. fix part two - you will also need to make 4 changes to podfile:

 - Add use_modular_headers! globally
 
 - Disable modular headers for DoubleConversion, Glog and Folly, like this PR [commit](https://github.com/kelsonpw/bug-reproduce-0.6.15/commit/c6e5a9d1e8e258f7c88e5a5d6f5bc8a04f9c6f0c#diff-281ded35b124f5160d0a57e47e521ee6f49f233933e091a0d33f3fd42a74abc8) for my test app.

I'm pretty sure this will fix your problem, if you dont mind just let me know after trying if youre having any issues.

**Comment by kelsonpw** [comment]
Here is a commit by commit example of getting it to work with 0.61.4: https://github.com/kelsonpw/AmpRN-0.61.4-Example/commits/main

**Comment by ALPNP** [comment]
Problem solved. Thanks for the help. Have a nice day.
