### ISSUE TITLE
Cannot read property 'setLibraryName' of undefined

### ISSUE THREAD

**Issue by burningraven06** [amplitude/Amplitude-ReactNative#61]
Hi, 

With the new version of Amplitude/ReactNative, I can't even initialize the library. I keep getting the error
``Cannot read property 'setLibraryName' of undefined``

Any clue on how to get fixed?

**Comment by kelsonpw** [comment]
Can you please provide: React Native version, and Node version?

**Comment by kelsonpw** [comment]
Can you please provide: React Native version, Node version, and platform (iOS/android)? We support RN 0.61 and above and we have documentation in the setup guide for older versions.

**Comment by kelsonpw** [comment]
Can you please provide: React Native version, and Node version? We officially support RN 0.61 and greater.  We have documentation in our setup guide for older RN versions that require some configuratio [here](https://developers.amplitude.com/docs/react-native-setup#installation) under troubleshooting.

**Comment by burningraven06** [comment]
I'm running React Native version 0.63.3.

When I try 
``Amplitude.getInstance().init(<API_KEY>)``

I get that error.

**Comment by kelsonpw** [comment]
Have you ran pod install in your Apps iOS directory and are you on @amplitude/react-native@0.2.11 (latest)?  If not would you mind sharing more information and provide a code sample?  The SDK works on many 0.63.x projects.

**Comment by kelsonpw** [comment]
We can only provide support if we have the necessary information, at the moment it's impossible to provide suggestions.

**Comment by burningraven06** [comment]
I have installed @amplitude/react-native
``version "2.0.11", "2.0.9", "2.0.7"``

but nothing helped.

And I'm working on an android app.

**Comment by burningraven06** [comment]
``
import { Amplitude } from '@amplitude/react-native';
const instance = Amplitude.getInstance();
instance.init(<API_KEY>);
instance.logEvent('SOMETHING TO TEST');

``

I get that error even after commenting out lines 3 / 4.

**Comment by kelsonpw** [comment]
@burningraven06 are you using expo?

**Comment by burningraven06** [comment]
No, I'm not

**Comment by kelsonpw** [comment]
@burningraven06 In that case, there is something specific to your project's code that is causing the native bridge to break.  This is unrelated to the library, as react-native 0.63.3 and @amplitude/react-native 2.0.11 function properly on Android.  I created an example project here that shows this functioning, take a look at the commit history and see if you are missing anything.  Other than that we are unable to provide support for code causing issues unrelated to the library.

https://github.com/kelsonpw/Amplitude-RN-0.63.3-Demo

**Comment by jwbackhouse** [comment]
@burningraven06 If you've not resolved this, we just encountered the same issue and managed to fix it by running
```sh
npx react-native link @amplitude/react-native
```
This issue for us was that the Amplitude SDK wasn't being automatically linked (as it should in RN 0.61+), so whilst this is the 'old' way of doing things it fixed the issue 👍🏼
