### ISSUE TITLE
Amplitude-ReactNative causes Jest tests to fail

### ISSUE THREAD

**Issue by odedmagger** [amplitude/Amplitude-ReactNative#65]
I recently migrated my RN project from Amplitude-Javascript to Amplitude-ReactNative, version 2.0.12 .
The project uses Typescript, and Jest serves as the Testing Framework.

When I run the project on a device, everything works perfectly.

However, when I run tests, for each test suite that includes analytics-calling code, I get a similar error:

Calling `jest MyComponent-test`:

```
app/core/MyModule/MyComponent-test.tsx
  ● Test suite failed to run

    Cannot find module '../package.json' from 'node_modules/@amplitude/react-native/lib/commonjs/constants.js'

    Require stack:
      node_modules/@amplitude/react-native/lib/commonjs/constants.js
      node_modules/@amplitude/react-native/lib/commonjs/index.js
      app/core/analytics/analytics.ts
      app/core/analytics/index.ts
      app/core/MyModule/MyComponent.tsx
      app/core/MyModule/MyComponent-test.tsx

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/@amplitude/react-native/lib/commonjs/constants.ts:1:1)
```

The `lib/commonjs/ directory indeed does not contain a `package.json`.

I followed the migration instructions [here](https://github.com/amplitude/Amplitude-ReactNative/blob/main/MIGRATION_GUIDE.md) to the letter.

Is there anything I'm missing, and can fix on my end?

**Comment by lourencogui** [comment]
Same here

**Comment by yuhao900914** [comment]
We fix this issue in the new release. 
Thanks for your patient.

**Comment by kelsonpw** [comment]
@lourencogui one thing to remember is this library is not pure javascript, it heavily relies on the bridge to Java/swift code.  Without that the library will break in an environment like Jest that runs in node.  You will need to mock the native module, something like https://stackoverflow.com/questions/41339996/how-to-test-a-react-native-component-that-imports-a-custom-native-module-with-je

**Comment by kelsonpw** [comment]
https://github.com/amplitude/Amplitude-ReactNative/blob/main/src/types.ts has an interface `AmplitudeReactNativeModule` that shows what the type definition of the underlying native methods are in NativeModules

**Comment by kelsonpw** [comment]
@lourencogui  It might be easier to just mock the javascript library, like this: https://github.com/kelsonpw/TestingAmpRN/blob/main/__tests__/App-test.tsx

cc @yuhao900914
