### ISSUE TITLE
Docs doesn't work

### ISSUE THREAD

**Issue by vinters768** [amplitude/Amplitude-ReactNative#68]
Setup guide and other related documentation does not work. Not an issue on the SDK part of things, but still without it, pretty hard to implement the SDK, so it's a bit related.
<img width="1792" alt="Screenshot 2021-04-16 at 08 51 40" src="https://user-images.githubusercontent.com/13395036/114977882-1aae2900-9e91-11eb-92c4-05e8df194c09.png">

https://developers.amplitude.com/docs/react-native-setup

**Comment by dantetam** [comment]
Hello @vinters768 ,

Our bad. Thanks for bringing this up. The SDK team is currently revamping the entire documentation for all the SDKs. We'll take care of this very soon.

Dante

**Comment by yuhao900914** [comment]
Hi @vinters768 ,
Thanks for letting us know, the page has linked back to the previous [URL](https://developers.amplitude.com/docs/react-native-setup).
