### ISSUE TITLE
How to change minTimeBetweenSessionsMillis from js or sessionTimeout? 

### ISSUE THREAD

**Issue by MikePodgorniy** [amplitude/Amplitude-ReactNative#70]
How to change minTimeBetweenSessionsMillis from js or sessionTimeout?

**Comment by yuhao900914** [comment]
Hi @MikePodgorniy, thanks for the new feature suggestion. We will make this on schedule soon.

**Comment by yuhao900914** [comment]
Hi @MikePodgorniy  
Want to give you an update about this feature. It has been implemented in the latest react native version.

**Comment by MikePodgorniy** [comment]
@yuhao900914 Thank you!
