### ISSUE TITLE
Support React Native Web

### ISSUE THREAD

**Issue by slamacchia** [amplitude/Amplitude-ReactNative#71]
Would it be possible to add support for [React Native Web](https://necolas.github.io/react-native-web/docs/)?

**Comment by kelsonpw** [comment]
We use native bridging so our typescript code can access swift/java methods from our iOS/Android SDK's.  This would not function in a web environment.


https://github.com/kelsonpw/Amplitude-React-Native-Web-Example
https://github.com/kelsonpw/Amplitude-React-Native-Web-Example/blob/350199fc679748957590860db448ee323922a90c/src/AmplitudeUtils.js

My suggestion for support react native web is to use dynamic imports with amplitude-js.  Here are is an example of how to get that to work:
![image](https://user-images.githubusercontent.com/17172317/115925367-dcd37680-a435-11eb-8993-9ee8ef429eb0.png)

**Comment by kelsonpw** [comment]
To answer the original question, no we cannot support RNW in this SDK but it is possible to use Amplitude SDK's to instrument a react-native-web app as demonstrated above.

**Comment by kelsonpw** [comment]
closing this out as we cannot implement this

**Comment by gwmccull** [comment]
Just wanted to add mention the approach we took for RNW. We didn't want to worry about the differences between the two SDKs so we created an interface for a generic Amplitude client that only contains the functions supported by both SDKs. That client is then passed into our RNW components from either the parent React web app or React Native mobile app. Then our RNW components use that client knowing that anything in there is safe for both platforms

**Comment by felpsio** [comment]
I tried @kelsonpw approach in my react-native-web app.

Just copied the exact wrapper (and changed the API_KEY) and inside my main component: App.tsx I added a hook `useEffect` that calls `initAmplitude Instance`. But I'm getting the following error:


```
amplitude.ts:9 Uncaught (in promise) TypeError: _context.sent.getInstance is not a function
    at getAmplitudeInstance$ (amplitude.ts:9)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:294)
    at Generator.next (runtime.js:119)
    at tryCatch (runtime.js:63)
    at invoke (runtime.js:155)
    at runtime.js:165
```

Inside my `tsconfig.json` I have the following code:

```
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "strict": true,
    "module": "esnext",
    "baseUrl": ".",
  }
}
```

Any idea how to solve the problem and make this wrapper work? :)

**Comment by felpsio** [comment]
I figured out the problem. Probably due to my babel configuration I had to import the module using `default`.

I changed this part of the wrapper you provided:
```
const getAmplitudeInstance = async () => {
  if (Platform.OS === 'web') {
    return (await import('amplitude-js')).default.getInstance(); //added default
  }
  return (await import('@amplitude/react-native')).default.Amplitude.getInstance(); //added default. You may not need default here, test both cases
};
```
