### ISSUE TITLE
Module map file '<home>/Library/Developer/Xcode/DerivedData/<appname>/Build/Products/Debug-iphonesimulator/amplitude-react-native/amplitude_react_native.modulemap' not found

### ISSUE THREAD

**Issue by denniswon** [amplitude/Amplitude-ReactNative#82]
When I try to build using Xcode (v12.4), I get the error
```
Module map file '<home>/Library/Developer/Xcode/DerivedData/<appname>/Build/Products/Debug-iphonesimulator/amplitude-react-native/amplitude_react_native.modulemap' not found
```
But I can run `react-native run ios` fine. How can I fix this build error in Xcode?

**Comment by yuhao900914** [comment]
Hi @denniswon 
When you try to build in Xcdoe did you open xxx.xcworkspace instead of xxx. xcodeproj?

**Comment by denniswon** [comment]
Yes. Resolved it, and forgot about this. xcworkspace resolved it. thanks

**Comment by kale1d** [comment]
I have this error in appcenter when building the app. In my local environment works fine. Any solution?
