### ISSUE TITLE
How to set event level groups?

### ISSUE THREAD

**Issue by Mlu456** [amplitude/Amplitude-ReactNative#88]
The migration guide says you can emulate `logEventWithGroups` by calling `setGroup` before `logEvent`, but `setGroup` will add a **user** to a group. How could you add an **event** to a group with this function?

**Comment by qingzhuozhen** [comment]
Hi @Mlu456, `setGroup` will set user to certain group, so later events for this user will be connected to that group. `logEventWithGroups` was set the group on the event level, so by mean `calling setGroup before logEvent` it is to emulate the `logEventWithGroups`. Not quite the same, but it is a way to handle the transition.cc @yuhao900914
