### ISSUE TITLE
Some users, for some unknown reason, track with sessionId -1

### ISSUE THREAD

**Issue by RichLew** [amplitude/Amplitude-ReactNative#91]
Some users, for some unknown reason, track with sessionId -1 and library http/2.0
![image](https://user-images.githubusercontent.com/62145902/128206737-2d006a7d-fa10-43d2-bdf2-020da10d9cd6.png)

**Comment by yuhao900914** [comment]
Hi @RichLew, 
It's hard to reproduce the issue without enough information. Is this customer on Android or iOS. and also may I have your amplitude-reactnative version?
