### ISSUE TITLE
getSessionId is missing

### ISSUE THREAD

**Issue by vikjovanov** [amplitude/Amplitude-ReactNative#93]
Hi,

I just migrated to @amplitude/react-native^2.3.3 (from amplitude-js 7.x.x) and I discover that there is no more getSessionId function.
How can I get the sessionId with this package ?

Thanks

**Comment by qingzhuozhen** [comment]
Hi @vikjovanov, `getSessionId` is not implemented now. We will track and add the method. cc @yuhao900914

**Comment by yuhao900914** [comment]
We are planing to add this method for this sprint. Thanks. @vikjovanov.
