### ISSUE TITLE
Error on Build with gradle-7.2  - :amplitude_react-native

### ISSUE THREAD

**Issue by mayconline** [amplitude/Amplitude-ReactNative#95]
- Failure build using gradle 7.2  

Packages:
-  "@amplitude/react-native": "2.4.0",
- "react": "17.0.2",
- "react-native": "0.65.1",
- classpath("com.android.tools.build:gradle:7.0.2")
- distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-all.zip

Step Reproduce:

- npx react-native run-android
 
Error:
```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\PC\Documents\workspace\project\node_modules\@amplitude\react-native\android\build.gradle' line: 14

* What went wrong:
A problem occurred evaluating project ':amplitude_react-native'.
> Failed to apply plugin 'com.android.internal.library'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.
```

**Comment by yuhao900914** [comment]
Hi @mayconline, 
I don't think is our @amplitude/react-native issue. That's related to the android studio setting. 
https://stackoverflow.com/questions/68728918/error-android-gradle-plugin-requires-java-11-to-run-you-are-currently-using-ja. Hope this link can help you solve the issue. 
Thanks.

**Comment by mayconline** [comment]
thanks, sorry for the issue, 
i thought it was a amplitude issue, but this link helped me ^^, i was still using java 1.8.
